configMapGenerator:
  - name: codespeed-config-agent-settings
    files:
      - agent-config-additional-fields
    literals:
      - LOG_WRITER_ADDITIONAL_ARGS=--add-log=name=log1,interval=1,duration=18h
      - codespeed_executable=2.7.17-Kubernetes-one-log
