configMapGenerator:
  - name: codespeed-config-version
    namespace: agent-benchmark
    literals:
      - commit_sha1=99e0d136d79ac504fee63b8132714d395e3ac312
      - commit_date=2018-09-19 19:57:19